#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Fix PORT environment variable to be an integer (Railway compatibility)
if (isset($_ENV['PORT']) && is_string($_ENV['PORT'])) {
    $_ENV['PORT'] = (int) $_ENV['PORT'];
    putenv('PORT=' . $_ENV['PORT']);
}
if (isset($_SERVER['PORT']) && is_string($_SERVER['PORT'])) {
    $_SERVER['PORT'] = (int) $_SERVER['PORT'];
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
